apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-pvc-photo
  labels:
    app: lychee
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
