---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-pvc-db
  annotations:
    volume.beta.kubernetes.io/storage-class: database-storage
  labels:
    app: lychee
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: database-storage
 