---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-pv-claim-config
  annotations:
    volume.beta.kubernetes.io/storage-class: ci-storage
  labels:
    app: lychee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ci-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-pv-claim-photos
  annotations:
    volume.beta.kubernetes.io/storage-class: ci-storage
  labels:
    app: lychee
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ci-storage

