apiVersion: v1
kind: ConfigMap
metadata:
  name: lychee-config
  labels:
    app: lychee
    name: lychee-config
data:
  db_name: lychee
  db_user: dbuser
  user.ini: |
    max_execution_time = 200
    post_max_size = 200M
    upload_max_size = 200M
    upload_max_filesize = 20M
    max_file_uploads = 200
  config.php: |
    <?php

    // Database configuration
    $dbHost = '$DB_HOST';
    $dbUser = '$DB_USER';
    $dbPassword = '$DB_PASSWORD';
    $dbName = '$DB_NAME';
    $dbTablePrefix = '';
    
    ?>
    