apiVersion: apps/v1
kind: Deployment
metadata:
  name: lychee-mysql
  labels:
    app: lychee
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lychee
      tier: db
  template:
    metadata:
      labels:
        app: lychee
        tier: db
    spec:
      containers:
      - name: mysql
        image: pks-harbor.syddsc.local/library/mysql:latest
#        image: mysql:latest
        args: ["--ignore-db-dir=lost+found"]
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: lychee-config
              key: db_name
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: lychee-config
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lychee-secret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lychee-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: lychee-sql-persistent-storage
          mountPath: /var/lib/mysql
      - name: mysql-wavefront
        image: pks-harbor.syddsc.local/library/wavefront-sidecar:latest
        imagePullPolicy: Always
        env:
        - name: SERVICES
          value: mysql
        - name: WAVEFRONT_PROXY_HOST
          value: 192.168.192.248
        - name: MONITOR_INTERVAL
          value: 30s
        - name: CLUSTER_NAME
          value: production
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace        
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_ACCOUNT
          value: root
        - name: SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lychee-secret
              key: password
        volumeMounts:
          - name: podinfo
            mountPath: /var/podinfo
            readOnly: false
      volumes:
      - name: lychee-sql-persistent-storage
        persistentVolumeClaim:
          claimName: lychee-pvc-db
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels

