apiVersion: apps/v1
kind: Deployment
metadata:
  name: lychee-web
  labels:
    app: lychee
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lychee
      tier: frontend
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: lychee
        tier: frontend
    spec:
      containers:
      - name: lychee
        image: pks-harbor.syddsc.local/library/lychee-web:latest
#        - image: davlloyd/lychee-web:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: lychee-mysql-service
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: lychee-config
              key: db_name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: lychee-config
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lychee-secret
              key: password
        ports:
        - containerPort: 80
          name: lychee
        volumeMounts:
        - name: lychee-volume-photos
          mountPath: /photos
        - name: config-file
          mountPath: /config/lychee/config.php
          subPath: config.php
        - name: config-file
          mountPath: /config/lychee/user.ini
          subPath: user.ini
      - name: lychee-wavefront
        image: pks-harbor.syddsc.local/library/wavefront-sidecar:latest
        imagePullPolicy: Always
        env:
        - name: SERVICES
          value: nginx
        - name: WAVEFRONT_PROXY_HOST
          value: 192.168.192.248
        - name: MONITOR_INTERVAL
          value: 30s     
        - name: CLUSTER_NAME
          value: production
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace        
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
          - name: podinfo
            mountPath: /var/podinfo
            readOnly: false
      volumes:
      - name: lychee-volume-photos
        persistentVolumeClaim:
          claimName: lychee-pvc-photo   
      - name: config-file
        configMap:
          name: lychee-config
      - name: podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
