apiVersion: v1
kind: Service
metadata:
  name: lychee-service-web
  labels:
    app: lychee
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: lychee
    tier: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer
