apiVersion: apps/v1
kind: Deployment
metadata:
  name: lychee-web
  labels:
    app: lychee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lychee
      tier: frontend
  template:
    metadata:
      labels:
        app: lychee
        tier: frontend
    spec:
      containers:
      - name: lychee
        image: pks-harbor.syddsc.local/library/lychee-web:latest
#        - image: davlloyd/lychee-web:latest
        env:
        - name: DB_HOST
          value: lychee-mysql-service
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: lychee-config
              key: db_name
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: lychee-config
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lychee-secret
              key: password
        ports:
        - containerPort: 80
          name: lychee
        volumeMounts:
        - name: lychee-volume-photos
          mountPath: /pictures
        - name: lychee-volume-config
          mountPath: /config
#        - name: config-file
#          mountPath: /config/lychee/config.php
#          subPath: config.php
        - name: config-file
          mountPath: /config/lychee/user.ini
          subPath: user.ini
      nodeSelector:
        node: "node1"
      volumes:
      - name: lychee-volume-photos
        persistentVolumeClaim:
          claimName: lychee-pv-claim-photos
      - name: lychee-volume-config
        persistentVolumeClaim:
          claimName: lychee-pv-claim-config
      - name: config-file
        configMap:
          name: lychee-config

