apiVersion: v1
kind: ConfigMap
metadata:
  name: lychee-config
  labels:
    app: lychee
    name: lychee-config
data:
  db_name: lychee
  db_user: root
  user.ini: |
    max_execution_time = 200
    post_max_size = 200M
    upload_max_size = 200M
    upload_max_filesize = 20M
    max_file_uploads = 200
  config.php: |
    <?php

    // Database configuration
    $dbHost = getenv('DB_HOST');
    $dbUser = getenv('DB_USER');
    $dbPassword = getenv('DB_PASSWORD');
    $dbName = getenv('DB_NAME');
    $dbTablePrefix = '';

    ?>

---

apiVersion: v1
kind: Secret
metadata:
  name: lychee-secret
  labels:
    app: lychee
type: Opaque
data:
  username: cm9vdA==
  password: cGFzc3dvcmQ=
  