apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-pv-photo-nfs
  labels:
    app: lychee
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
