kind: Service
apiVersion: v1
metadata:
  name: lychee-web-service
  labels:
    app: lychee
    tier: frontend
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: lychee
    tier: frontend
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  #sessionAffinity: None
  sessionAffinity: ClientIP
  type: LoadBalancer
