apiVersion: v1
kind: PersistentVolume
metadata:
  name: lychee-pv-photo-nfs
  labels:
    app: lychee
    tier: frontend
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.187.250
    path: "/lychee/album-dev"
    readOnly: false 

