kind: Service
apiVersion: v1
metadata:
  name: lychee-web-service
  labels:
    app: lychee
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: lychee
    tier: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  #sessionAffinity: None
  sessionAffinity: ClientIP
  type: LoadBalancer
